### PR TITLE
Adding support for pre-commit framework

### PR DESCRIPTION
**Pull request by jdyke**
Adding support for pre-commit framework

*Issue #, if available:* #115

*Description of changes:* Added the required .pre-commit-hooks.yaml file to support the pre-commit framework detailed here: https://pre-commit.com/ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by akinnane** [comment]
Hi @mtdowling, could you merge this PR, please?

**Comment by jarednielsen** [comment]
+1 @mtdowling, would love if you merge this PR and cut a new release.

**Comment by rahul003** [comment]
+1

**Comment by sparr** [comment]
Tip for future PRs: If you prefix the issue number with some variation of "fix", "close", or "resolve", then the issue will be closed when the PR is merged. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
