### PR TITLE
Add advance configuration section to readme

### PR DESCRIPTION
**Pull request by dhoer**
The advanced configuration section in this wonderful article made me realize the power of git-secrets: http://ebi-cloud-portal.readthedocs.io/en/latest/securing_credentials.html#advanced-configuration

I think it would be beneficial to add this information to the readme.

### CODE REVIEW

**Comment by hyandell** [comment]
Can't just copy from someone else's repo/documentation though. Did you get permission or find a license for it?

**Comment by dhoer** [comment]
They were kind enough to grant us permission.

**Comment by hyandell** [comment]
Thank you Dennis :)

**Comment by hyandell** [comment]
@mtdowling  This looks good Michael, though I think the scan-history bit is redundant so I would remove that after merge. What do you think?

**Comment by mtdowling** [comment]
Thanks!

**Pull request merged**
