### PR TITLE
Feature/fix scan files

### PR DESCRIPTION
**Pull request by t13a**
Fix problem #66 that not scanned except the first file

-  filenames are treated as array
-  add missing redirection in test case

### CODE REVIEW

**Comment by t13a** [comment]
I confirmed that the argument handling differs between `git secrets --scan files...` and `pre-commit` on testing environment (Ubuntu 14.04 LTS). The former treats as multiple arguments. On the other hand the later treats as single one (separated by line).

**Comment by mmizutani** [comment]
@mtdowling I do not want to bother you, but could you have a glance at this pull request to see if it can be merged when you have spare time?

**Comment by rix0rrr** [comment]
Ping on this. This broken feature is limiting our ability to run `git-secrets` in a CodeBuild build step (since that build is not done in a git working copy)

**Comment by mtdowling** [comment]
Thanks so much and sorry for the delay. We need to get a bash testing matrix in place to catch these issues.

**Pull request merged**
