### PR TITLE
Writing instructions for how to get git-secrets to work for Windows

### PR DESCRIPTION
**Pull request by jschwarzwalder**
*Issue #, if available:*
#83 

*Description of changes:*
Adding instructions for how to use git-secrets to work on a Windows 10 machine. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jschwarzwalder** [comment]
@mtdowling Please let me know if you would like any changes to the instructions.

**Comment by costleya** [comment]
I see you came across the same workflow as I did. I turned these instructions into a PowerShell script in https://github.com/awslabs/git-secrets/pull/88

**Comment by jschwarzwalder** [comment]
@mtdowling Will you be able to review #87 or #88 for Windows Users?

Thank you

**Comment by mtdowling** [comment]
Thanks for the PR. I merged #88 in lieu of this PR. Let me know if there's something else in this PR that's not in #88 that needs to be merged.

**Pull request closed without merging**
